version: '3'

services:
  instagram-api-clone:
    container_name: instagram-api-clone
    build: .
    ports:
    - "3333:3333"
    links:
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"