version: '3'

services:
  instagram-api-clone:
    build: .
    environment:
       - DB_HOST=mongodb://mongo:27017/instagram
       - APP_PORT=3333
    ports:
    - "3333:3333"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"